version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_expense_tracker
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: expense_tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
