version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_expense_tracker
    ports:
      - "5673:5672"
      - "15673:15672" # management UI
    environment:
      RABBITMQ_DEFAULT_USER: expense
      RABBITMQ_DEFAULT_PASS: expense

  maildev:
    image: maildev/maildev
    container_name: maildev_expense_tracker
    ports:
      - "1025:1025"   # SMTP
      - "1080:1080"   # Web UI

